### ISSUE TITLE
Export geoJson

### ISSUE THREAD

**Issue by NikolaVeber** [spupyrev/gmap#7]
Hi guys, 

thank you very much for your work. I was looking for a tool to create a map representation of data stored in graphs, the gmap seems to be perfect fit.

As I intend to use the map in Kepler.gl to create additional overlays, is there a possibility to export the created map as GeoJSON or some equivalent format?

Thanks!
Nikola

**Comment by spupyrev** [comment]
Hi,
We don't currently export maps to geojson format, unfortunately. Internally the maps are stored as DOT/SVG files, which can be accessed via http://gmap.cs.arizona.edu/map/9611/svg or http://gmap.cs.arizona.edu/map/9611/dot. You would need to have your own converter to create json files.
